sudo: required
dist: trusty

services:
 - docker

addons:
  apt:
    packages:
    - nodejs
    - jq

install:
  - npm install -g dockerfile_lint

before_script:
  - mkdir $HOME/bin
  - export PATH=$PATH:$HOME/bin
  - tmp=`mktemp`
  - echo 'DOCKER_OPTS="$DOCKER_OPTS --insecure-registry 172.30.0.0/16"' > ${tmp}
  - sudo mv ${tmp} /etc/default/docker
  - sudo mount --make-shared /
  - sudo service docker restart

script:
  - make lint
  - make
  - make test
  - wget `curl -s https://api.github.com/repos/openshift/origin/releases/latest | jq -r ".assets[] | select(.name | test(\"linux-64bit\")) | .browser_download_url" | grep -i client-tools`
  - tar xvfz `ls openshift-origin-client-tools-*.tar.gz` --strip-components=1 -C $HOME/bin
  - oc cluster up
  - sleep 5
  - oc login -u system:admin
  - oc rollout status -w dc/docker-registry -n default
  - export REGISTRY_IP=`oc get svc/docker-registry -o json -n default | jq -r '.spec.clusterIP'`
  - oc login -u developer -p developer
  - make openshift-test REGISTRY=${REGISTRY_IP}
  - oc version
