sudo: required
dist: trusty

#env:
#  - OS_TYPE=centos7

services:
 - docker

addons:
  apt:
    packages:
    - nodejs

install:
  - npm install -g dockerfile_lint

before_script:
  - dockerfile_lint -f Dockerfile
  - dockerfile_lint -f Dockerfile.rhel7

script:
  - make
