sudo: required
dist: trusty

env:
  - OS_TYPE=centos7

services:
 - docker

addons:
  apt:
    packages:
    - nodejs

install:
  - npm install -g dockerfile_lint

before_script:
  - dockerfile_lint -f Dockerfile.${OS_TYPE}

script:
  - make
